name: assiduo.us
favicon: null
layout_spectrum: 0.7132380355615169
typography_spectrum: 0.745462115155533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.711659079650417
  lightness: 0.33866570284590125
  saturation: 0.11955361859872937
  rhythmicContrast: 0.6267776235472411
purpose: []
